<a href="https://colab.research.google.com/github/Dimasputraangrh/bunga/blob/main/DESICION%20TREE%20FIX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

TAMPILKAN DATASET

In [2]:
# Load dataset
data = pd.read_csv("/content/youtube-top-100-songs-2025.csv")

# Lihat 20 data pertama
display(data.head(20))

# Cek struktur data
data.info()

title  \
0    ROSÉ & Bruno Mars - APT. (Official Music Video)   
1   Lady Gaga, Bruno Mars - Die With A Smile (Offi...   
2   Reneé Rapp - Leave Me Alone (Official Music Vi...   
3   Billie Eilish - BIRDS OF A FEATHER (Official M...   
4             Reneé Rapp - Mad (Official Music Video)   
5                        Sabrina Carpenter - Espresso   
6      Lady Gaga - Abracadabra (Official Music Video)   
7        Ed Sheeran - Sapphire (Official Music Video)   
8              yung kai - blue (official music video)   
9      Billie Eilish - WILDFLOWER (BILLIE BY FINNEAS)   
10  Zillionaire Doe - How It's Going (Official Video)   
11            Alex Warren - Ordinary (Official Video)   
12           Kendrick Lamar - luther (Official Audio)   
13  Shaboozey - A Bar Song (Tipsy) [Official Visua...   
14                       Kendrick Lamar - Not Like Us   
15  LISA - BORN AGAIN feat. Doja Cat & RAYE (Offic...   
16                C'zah - Vent | Official Music Video   
17                Lola Young - Messy (Official Video)   
18    Teddy Swims - Bad Dreams (Official Music Video)   
19          JENNIE, Doechii - ExtraL (Official Video)   

                                            fulltitle  \
0    ROSÉ & Bruno Mars - APT. (Official Music Video)   
1   Lady Gaga, Bruno Mars - Die With A Smile (Offi...   
2   Reneé Rapp - Leave Me Alone (Official Music Vi...   
3   Billie Eilish - BIRDS OF A FEATHER (Official M...   
4             Reneé Rapp - Mad (Official Music Video)   
5                        Sabrina Carpenter - Espresso   
6      Lady Gaga - Abracadabra (Official Music Video)   
7        Ed Sheeran - Sapphire (Official Music Video)   
8              yung kai - blue (official music video)   
9      Billie Eilish - WILDFLOWER (BILLIE BY FINNEAS)   
10  Zillionaire Doe - How It's Going (Official Video)   
11            Alex Warren - Ordinary (Official Video)   
12           Kendrick Lamar - luther (Official Audio)   
13  Shaboozey - A Bar Song (Tipsy) [Official Visua...   
14                       Kendrick Lamar - Not Like Us   
15  LISA - BORN AGAIN feat. Doja Cat & RAYE (Offic...   
16                C'zah - Vent | Official Music Video   
17                Lola Young - Messy (Official Video)   
18    Teddy Swims - Bad Dreams (Official Music Video)   
19          JENNIE, Doechii - ExtraL (Official Video)   

                                          description  view_count  \
0   ROSÉ & Bruno Mars - APT.\nDownload/stream: ht...  2009014557   
1   MAYHEM OUT NOW\nhttp://ladygaga.com \n \nListe...  1324833300   
2   Listen to “BITE ME”, the new album from Reneé ...     2536628   
3   Listen to HIT ME HARD AND SOFT: https://billie...   558329099   
4   Listen to “BITE ME”, the new album from Reneé ...     2113548   
5   Music video by Sabrina Carpenter performing Es...   472570966   
6   MAYHEM OUT NOW\nhttp://ladygaga.com\n \nDirect...   191073418   
7   Listen to 'Sapphire' now: https://es.lnk.to/sa...   184696317   
8   Stream my track and follow me on socials: http...   187281056   
9   HIT ME HARD AND SOFT (WITH ALL ISOLATED VOCALS...    40408980   
10  Stream "How It's Going": https://zillionairedo...     1198540   
11  'You'll Be Alright, Kid' out now: https://alex...   147871443   
12  Kendrick Lamar “GNX” is available now: https:/...   142084039   
13  Pre order the album "Where I've Been, Isn't Wh...   288277902   
14  Kendrick Lamar “Not Like Us”\nDirected by Dave...   397228595   
15  Stream LISA’s new single “Born Again” feat. Do...   115058148   
16  C'zah - Vent | Official Music Video\nProduced ...       12089   
17  My new album 'I'm Only F**cking Myself' is out...   110991682   
18  Stream "Bad Dreams" now: https://TeddySwims.ln...   160421970   
19  Official music video for “ExtraL” by JENNIE & ...    92973980   

        categories                                               tags  \
0            Music  YG Entertainment;YG;와이지;K-pop;BLACKPINK;블랙핑크;블...   
1            Music                Lady Gaga;Bruno Mars;I

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   title                   100 non-null    object
 1   fulltitle               100 non-null    object
 2   description             100 non-null    object
 3   view_count              100 non-null    int64 
 4   categories              100 non-null    object
 5   tags                    85 non-null     object
 6   duration                100 non-null    int64 
 7   duration_string         100 non-null    object
 8   live_status             100 non-null    bool  
 9   thumbnail               100 non-null    object
 10  channel                 100 non-null    object
 11  channel_url             100 non-null    object
 12  channel_follower_count  100 non-null    int64 
dtypes: bool(1), int64(3), object(9)
memory usage: 9.6+ KB


KATEGORIKAN

In [3]:
df = pd.read_csv("/content/youtube-top-100-songs-2025.csv")

# Kategori durasi
def kategori_durasi(d):
    if d < 180:
        return "Pendek"
    elif d <= 300:
        return "Sedang"
    else:
        return "Panjang"

df['durasi_kategori'] = df['duration'].apply(kategori_durasi)

# Kelas view
conditions = [
    df['view_count'] < 100_000_000,
    (df['view_count'] >= 100_000_000) & (df['view_count'] < 1_000_000_000),
    df['view_count'] >= 1_000_000_000
]
choices = ['Rendah', 'Sedang', 'Tinggi']
df['kelas_view'] = np.select(conditions, choices, default='')

ENCODING

In [4]:
X = df[['categories', 'durasi_kategori', 'channel', 'channel_follower_count']]
y = df['kelas_view']

# Encode output
label_y = LabelEncoder()
y_enc = label_y.fit_transform(y)

# One-Hot Encoding input
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

encoder = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'),
         ['categories', 'durasi_kategori', 'channel']),
        ('num', 'passthrough', ['channel_follower_count'])
    ]
)

X_encoded = encoder.fit_transform(X)
# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_enc, test_size=0.2, random_state=42
)

TRAIN DECISION TREE

In [7]:
model = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state=42)

EVALUASI MODEL

In [8]:
y_pred = model.predict(X_test)

print(classification_report(
    y_test, y_pred,
    target_names=label_y.classes_
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

      Rendah       0.81      0.87      0.84        15
      Sedang       0.25      0.25      0.25         4
      Tinggi       0.00      0.00      0.00         1

    accuracy                           0.70        20
   macro avg       0.35      0.37      0.36        20
weighted avg       0.66      0.70      0.68        20

Confusion Matrix:
[[13  2  0]
 [ 3  1  0]
 [ 0  1  0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


PREDIKSI MANUAL

In [10]:
print("=== INPUT MANUAL DECISION TREE ===")

kategori = input("Masukkan kategori musik: ").title()
durasi = input("Masukkan durasi (Pendek/Sedang/Panjang): ").title()
penyanyi = input("Masukkan nama penyanyi (1 nama): ").title()
subscriber = int(input("Masukkan jumlah follower channel (angka): ")) # Added line to get subscriber input

input_df = pd.DataFrame({
    'categories': [kategori],
    'durasi_kategori': [durasi],
    'channel': [penyanyi],
    'channel_follower_count': [subscriber]
})

input_enc = encoder.transform(input_df)

pred = model.predict(input_enc)
prob = model.predict_proba(input_enc)

kelas = label_y.inverse_transform(pred)

print("\nHasil Prediksi View:", kelas[0])
print("\nProbabilitas:")
for i, k in enumerate(label_y.classes_):
    print(f"{k}: {prob[0][i]*100:.2f}%")

=== INPUT MANUAL DECISION TREE ===
Masukkan kategori musik: musik
Masukkan durasi (Pendek/Sedang/Panjang): sedang
Masukkan nama penyanyi (1 nama): Teddy Swims - Bad Dreams
Masukkan jumlah follower channel (angka): 6070000

Hasil Prediksi View: Rendah

Probabilitas:
Rendah: 81.82%
Sedang: 18.18%
Tinggi: 0.00%
